var Log = require('./')

var logAll   = new Log({ name : 'test-all',  level : Log.all  })
var logTrace = new Log({ name : 'test-trace',  level : Log.trace  })
var logDebug = new Log({ name : 'test-debug',  level : Log.debug  })
var logInfo2 = new Log({ name : 'test-info', level : Log.info })
var logInfo1 = new Log({ name : 'test-info', })
var logWarn  = new Log({ name : 'test-warn', level : Log.warn })
var logError = new Log({ name : 'test-error', level : Log.error })
var logFatal = new Log({ name : 'test-fatal', level : Log.fatal })
var logNone  = new Log({ name : 'test-none', level : Log.none })

logToThis('all',  logAll)
logToThis('trace',  logTrace)
logToThis('debug',  logDebug)
logToThis('info2', logInfo2)
logToThis('info1', logInfo1)
logToThis('warn', logWarn)
logToThis('error', logError)
logToThis('fatal', logFatal)
logToThis('none', logNone)

function logToThis(type, log) {
  console.log('---')
  console.log('Type:', type)

  log.fatal('This is a Fatal Message')
  log.fatal({ o : 123, b : 'c' }, 'This is a Fatal Message')
  log.error('This is a Error Message')
  log.error({ o : 123, b : 'c' }, 'This is a Error Message')
  log.warn('This is a Warn Message')
  log.warn({ o : 123, b : 'c' }, 'This is a Warn Message')
  log.info('This is a Info Message')
  log.info({ o : 123, b : 'c' }, 'This is a Info Message')
  log.debug('This is a Debug Message')
  log.debug({ o : 123, b : 'c' }, 'This is a Debug Message')
  log.trace('This is a Trace Message')
  log.trace({ o : 123, b : 'c' }, 'This is a Trace Message')
}
